# How many distinct terms are in the sequence generated by a^(b) for 2 <= a <= 100 and 2 <= b <= 100?

# Note: (a^b1)(a^b2) = a^(b1+b2)

require 'euler.rb'

terms = Array.new()


2.upto(100) do |a|
  2.upto(100) do |b|
    terms << a**b
  end
end

puts terms.uniq.size