// Project Euler
//
// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle
// number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
//
// We can see that 28 is the first triangle number to have over five divisors.
//
// What is the value of the first triangle number to have over five hundred divisors?

use super::shared;

pub fn run() {
    println!("Running problem 12.");

    println!("{}", shared::count_factors(76576500));

    let mut triangle: u64 = 0;
    for n in 1..10000000001 {
        triangle += n;
        if n % 500 == 0 {
            println!("Hit {}", n);
        }

        let f: u64 = shared::count_factors(triangle);
        if f > 500 {
            println!("triangle:{} = ({})", triangle, f);
            break;
        }
    }
}
