[package]
name = "rust"
version = "0.1.0"
authors = ["Thomas Sullivan <thomas.l.sullivan@vumc.org>"]
edition = "2018"

[dependencies]
num-traits = "0.2.8"
num = "0.2.0"
numbers = "0.1.2"
regex = "1"
rust-embed="4.2.0"
